version: '3'

services:
  ssh:
    image: rastasheep/ubuntu-sshd:18.04
    command: /usr/sbin/sshd -D -E /var/log/sshd
    ports:
      - "31338:22"
    networks:
      - br_default
      - br_internal
    volumes:
      - ./sshd_config:/etc/ssh/sshd_config

  hackmd:
    image: hackmdio/hackmd:1.2.0
    environment:
      HMD_DB_URL: postgres://hackmd:hackmdpass@postgres:5432/hackmd
    networks:
      - br_internal

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
    networks:
      - br_internal
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  br_default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/27
  br_internal:
    internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.237.0/27